
services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/heartbeat')"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  processor:
    build: 
      context: ./processor
      dockerfile: Dockerfile
    depends_on:
      - chroma
    volumes:
      - ${DOCUMENTS_PATH:-./documents}:/app/documents:ro
      - ./processor:/app
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
      - CHROMA_HOST=chroma:8000
      - EMBEDDING_MODEL=mxbai-embed-large
      - DOCUMENTS_PATH=/app/documents
      - BATCH_SIZE=10
      - OLLAMA_RETRIES=3
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    depends_on:
      - chroma
    volumes:
      - ./mcp-server:/app
    environment:
      - CHROMA_HOST=chroma:8000
      - OLLAMA_HOST=host.docker.internal:11434
      - EMBEDDING_MODEL=mxbai-embed-large
    ports:
      - "8002:8002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  chat-interface:
    build:
      context: ./chat-interface
      dockerfile: Dockerfile
    depends_on:
      - processor
    volumes:
      - ./chat-interface:/app
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
      - PROCESSOR_HOST=processor:8001
      - CHAT_MODEL=llama3.1:8b
    ports:
      - "8003:8003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

volumes:
  chroma_data: