
services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/heartbeat')"]
      interval: 10s
      timeout: 5s
      retries: 5

  processor:
    build: 
      context: ./processor
      dockerfile: Dockerfile
    depends_on:
      - chroma
    volumes:
      - ./documents:/app/documents:ro
      - ./processor:/app
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
      - CHROMA_HOST=chroma:8000
      - EMBEDDING_MODEL=mxbai-embed-large
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    depends_on:
      - chroma
    volumes:
      - ./mcp-server:/app
    environment:
      - CHROMA_HOST=chroma:8000
      - OLLAMA_HOST=host.docker.internal:11434
      - EMBEDDING_MODEL=mxbai-embed-large
    ports:
      - "8002:8002"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  chroma_data: